
# Allow japanese comment
AsciiComments:
  Enabled: false

# Allow "module::Class"
ClassAndModuleChildren:
  Enabled: false

# Disable Documentation
Documentation:
  Enabled: false

# Allow "and", "or"
AndOr:
  Enabled: false

# Allow long line
LineLength:
  Enabled: false

# Allow training blank line
TrailingBlankLines:
  Enabled: false

# Allow leading blank line
LeadingBlankLines:
  Enabled: false

# Allow empty lines
EmptyLines:
  Enabled: false

# Allow old hash syntax
HashSyntax:
  Enabled: false

# Allow unalign hash
AlignHash:
  Enabled: false

#
BracesAroundHashParameters:
  Enabled: false

ExtraSpacing:
  Enabled: false

TrailingSpaces:
  Enabled: false

# Allow empty comment
EmptyComment:
  Enabled: false

# Allow short method name
UncommunicativeMethodParamName:
  Enabled: false

AccessModifierDeclarations:
  Enabled: false

# Allow double quote string literal
StringLiterals:
  Enabled: false

SpaceAfterColon:
  Enabled: false

